"""initial_schema

Revision ID: 3dae7b8c24cb
Revises: 
Create Date: 2026-03-25 12:37:48.109929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dae7b8c24cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='unregistered', nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('system_prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('approved_tools', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('applies_to_agents', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('compliance_frameworks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('severity', sa.String(length=20), server_default='medium', nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('trigger_context', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('risk_score', sa.Integer(), server_default='0', nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('policy_name', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('risk_delta', sa.Integer(), server_default='0', nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hitl_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_event_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('notified_via', sa.String(length=50), nullable=True),
    sa.Column('notification_sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('response_deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audit_event_id'], ['audit_events.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hitl_reviews')
    op.drop_table('audit_events')
    op.drop_table('sessions')
    op.drop_table('policies')
    op.drop_table('agents')
    # ### end Alembic commands ###
